from __future__ import annotations

import sys
from collections.abc import Callable, Mapping
from typing import (
    Any,
    ClassVar,
    Literal,
    NoReturn,
    Sequence,
    Tuple,
    Type,
    TypeVar,
    Union,
    _GenericAlias,
    get_args,
    get_origin,
    get_type_hints,
)

from pytypehintcheck.typing import Annotated, NoneType


# -----------------------------------------------------------------------------
# Types
# -----------------------------------------------------------------------------

_HINT_TYPE = Any


# -----------------------------------------------------------------------------
# Functions
# -----------------------------------------------------------------------------

if sys.version_info < (3, 9):
    def _is_annotation(hint: Any) -> bool:  # noqa: ANN401
        meta = getattr(hint, '__metadata__', None)
        return isinstance(meta, Sequence) and len(meta) > 0

else:
    def _is_annotation(hint: Any) -> bool:  # noqa: ANN401
        return get_origin(hint) is Annotated


def _resolve_sub_types(hint: _HINT_TYPE) -> Tuple[TypeInfo, ...]:
    sub_types = []
    for arg in get_args(hint):
        if isinstance(arg, (type, _GenericAlias)) or arg is Ellipsis:
            sub_types.append(TypeInfo(arg))
    return tuple(sub_types)


def _raise_type_error(
    required_name: str,
    required_type: Type[Any],
    obj: Any            # noqa: ANN401
) -> NoReturn:
    msg = (
        f'Invalid type: {required_name} must be {required_type.__name__!r} but'
        f' is {type(obj).__name__!r}'
    )
    raise TypeError(msg)


def _raise_length_error(
    expect_len: int,
    actual_len: int,
    name: str
) -> NoReturn:
    name = (' ' + name).strip()
    msg = (
        f'Invalid length:{name} length is {actual_len} '
        f'but must be {expect_len}'
    )
    raise ValueError(msg)


# -----------------------------------------------------------------------------
# Classes
# -----------------------------------------------------------------------------

class TypeInfo:
    """
    The TypeInfo class analyses a hint generated by the `get_type_hints`
    function from typing.py.
    """

    call_params: tuple[TypeInfo, ...]
    """Tuple of TypeInfo objects describing the parameters of a callable."""

    call_returns: TypeInfo
    """
    Tuple of TypeInfo objects describing the return parameters of a callable.
    """

    is_annotation: bool
    """
    Flag: If True object is an Annotated type.
    See: https://docs.python.org/3/library/typing.html#typing.Annotated
    """

    is_any: bool
    """
    Flag: If True object can be Any object
    See: https://docs.python.org/3/library/typing.html#typing.Any
    """

    is_callable: bool
    """Flag: If True object is a callable."""

    is_class_var: bool
    """
    Flag: If True object is a ClassVar.
    See: https://docs.python.org/3/library/typing.html#typing.ClassVar
    """

    is_ellipsis: bool
    """
    Flag: If True object is the builtin Ellipses type (...)
    See: https://docs.python.org/3/library/stdtypes.html#the-ellipsis-object
    """

    is_literal: bool
    """
    Flag: If True object has a concrete value
    See: https://typing.python.org/en/latest/spec/literal.html
    """

    is_mapping: bool
    """Flag: If True object is Mapping"""

    is_none: bool
    """Flag: If True object is NoneType"""

    is_sequence: bool
    """Flag: If True object is a Sequence"""

    is_tuple: bool
    """Flag: If True object is a tuple"""

    is_type: bool
    """Flag: If True object is a type"""

    is_type_var: bool
    """
    Flag: If True object is a TypeVar
    See: https://typing.python.org/en/latest/spec/literal.html
    """

    is_union: bool
    """Flag: If True object can be one of a selection of predefined types"""

    literal_values: tuple[Any, ...]
    """Tuple of concrete values an. Object must be one of these values."""

    metadata: tuple[Any, ...]
    """
    Tuple of metadata for an Annotated type.
    See: https://docs.python.org/3/library/typing.html#typing.Annotated
    """

    origin: Any
    """
    Result of the get_origin method.
    See: https://docs.python.org/3/library/typing.html#typing.get_origin
    """

    sub_types: tuple[TypeInfo, ...]
    """Tuple of TypeInfo objects describing possible subtypes"""

    type: Type | None
    """Actual type of the object"""

    __slots__ = (
        'call_params',
        'call_returns',
        'is_annotation',
        'is_any',
        'is_callable',
        'is_class_var',
        'is_ellipsis',
        'is_literal',
        'is_mapping',
        'is_none',
        'is_sequence',
        'is_tuple',
        'is_type',
        'is_type_var',
        'is_union',
        'literal_values',
        'metadata',
        'origin',
        'sub_types',
        'type'
    )

    def _repr(self, with_prefix: bool = True) -> str:
        result = f'{self.__class__.__name__}: ' if with_prefix else ''

        if self.is_type_var:
            result += 'TypeVar'
            if self.type is not None:
                result += f'[{TypeInfo(self.type)._repr(False)}]'
            return result

        if self.type is None:
            if self.is_ellipsis:
                result += '...'
            elif self.is_none:
                result += 'None'
            elif self.is_literal:
                lt = ', '.join(repr(v) for v in self.literal_values)
                result += f'Literal[{lt}]'

            # TODO: what else can this be?
            return result

        sub_types = None
        if len(self.sub_types):
            sub_types = ', '.join((st._repr(False) for st in self.sub_types))

        if self.is_union:
            return result + f'Union[{sub_types}]'

        result += self.type.__name__
        if sub_types is not None:
            result += f'[{sub_types}]'

        if self.is_callable:
            params = ', '.join((p._repr(False) for p in self.call_params))
            ret_type = self.call_returns._repr(False)
            result += f'[[{params}], {ret_type}]'

        return result

    def __repr__(self) -> str:
        return self._repr()

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, TypeInfo):
            return False

        for attr in TypeInfo.__slots__:
            if getattr(self, attr) != getattr(other, attr):
                return False

        for st_me, st_o in zip(self.sub_types, other.sub_types):
            if st_me != st_o:
                return False

        return True

    def __hash__(self) -> int:
        # TODO: calculate proper hash
        return 0

    def _slot_init(self, hint: _HINT_TYPE) -> None:
        self.type = None
        self.origin = None
        self.sub_types = ()
        self.is_any = hint is Any
        self.is_type = False
        self.is_mapping = False
        self.is_sequence = False
        self.is_tuple = False
        self.is_none = hint is NoneType or hint is None
        self.is_ellipsis = hint is Ellipsis
        self.is_annotation = False
        self.is_class_var = False
        self.is_type_var = False
        self.is_union = False
        self.is_literal = False
        self.literal_values: tuple[Any, ...] = ()
        self.is_callable = False
        self.call_params = ()
        self.call_returns = ()
        self.metadata: tuple[Any, ...] = ()

    def __init__(self, hint: _HINT_TYPE) -> None:
        """
        :@param hint:           A type hint generated by calling typings.py
                                `get_type_hints` function.
        """
        self._slot_init(hint)
        if self.is_any or self.is_none or self.is_ellipsis:
            return

        self.origin = get_origin(hint)
        self.is_type = self.origin is type
        self.is_class_var = self.origin is ClassVar
        self.is_literal = self.origin is Literal
        self.is_type_var = isinstance(hint, TypeVar)
        self.is_annotation = _is_annotation(hint)

        if self.is_annotation or self.is_class_var:
            self.metadata = getattr(hint, '__metadata__', (None, None))
            args = get_args(hint)
            if args != ():
                self.origin = None
                hint = args[0]

        elif self.is_literal:
            self.literal_values = get_args(hint)

        elif self.is_type:
            self.type = type
            self.sub_types = tuple((TypeInfo(a) for a in get_args(hint)))

        elif self.is_type_var:
            hint = hint.__bound__
            if hint is None:
                return

        self.is_union = self.origin is Union
        if self.is_union:
            _types = []
            sub_types = []
            for arg in get_args(hint):
                _types.append(get_origin(arg) or arg)
                sub_types.append(TypeInfo(arg))

            self.type = tuple(_types)
            self.sub_types = tuple(sub_types)
            return

        self.is_callable = self.origin is Callable
        if self.is_callable:
            self.type = self.origin
            param, return_type = get_args(hint)
            if not isinstance(param, Sequence):
                param = (param,)
            self.call_params = tuple([TypeInfo(a) for a in param])
            self.call_returns = TypeInfo(return_type)
            return

        self.type = self.origin or hint
        self.is_tuple = self.origin is tuple
        if isinstance(self.origin, type):
            self.is_mapping = issubclass(self.origin, Mapping)
            self.is_sequence = issubclass(self.origin, Sequence)
        self.sub_types = _resolve_sub_types(hint)

    def _union_check(
        self,
        obj: Any,  # noqa: ANN401
        name: str,
        do_raise: bool = False
    ) -> bool:
        for ti in self.sub_types:
            if ti._check_instance(obj, name, do_raise):
                return True
        return False

    def _tuple_check(
        self,
        obj: Any,  # noqa: ANN401
        name: str,
        do_raise: bool = False
    ) -> bool:
        _type = self.sub_types[0]
        num_sub_types = len(self.sub_types)
        if _type.is_ellipsis:
            # tuple[...] -> Variable length and any type allowed
            return True

        if num_sub_types == 2 and self.sub_types[1].is_ellipsis:  # noqa: PLR2004
            # for example tuple[int, ...]
            return self._sequence_check(obj, name, do_raise)

        if len(self.sub_types) != len(obj):
            if do_raise:
                _raise_length_error(len(self.sub_types), len(obj), name)
            return False

        for index, (tpl_type, obj_item) in enumerate(zip(self.sub_types, obj)):
            if not tpl_type.check(obj_item, f'{name}[{index}]', do_raise):
                return False

        return True

    def _sequence_check(
        self,
        obj: Sequence[Any],
        name: str,
        do_raise: bool = False
    ) -> bool:
        value_type = self.sub_types[0]
        for index, value in enumerate(obj):
            if not value_type.check(
                value,
                f'{name}[{index}]',
                do_raise=do_raise
            ):
                return False
        return True

    def _mapping_check(
        self,
        obj: Mapping[Any, Any],
        name: str,
        do_raise: bool = False
    ) -> bool:
        key_type, value_type = self.sub_types
        for key, value in obj.items():
            if not key_type.check(key, name):
                if do_raise:
                    ...
                return False
            if not value_type.check(
                value,
                f'{name}[{key}]',
                do_raise=do_raise
            ):
                return False
        return True

    def _callable_check(
        self,
        obj: Callable,
        name: str,          # noqa  TODO: raise error with callable name
        do_raise: bool = False
    ) -> bool:
        hints = get_type_hints(obj)
        call_return = TypeInfo(hints.pop('return', None))
        call_params = tuple((TypeInfo(p) for p in hints.values()))

        if len(self.call_params) > 0 and self.call_params[0].is_ellipsis:
            return self.call_returns == call_return

        if self.call_returns == call_return and \
           self.call_params == call_params:
            return True

        if do_raise:
            ...

        return False

    def _check_instance(  # noqa: PLR0911, PLR0912  TODO: simplify code
        self,
        obj: Any,  # noqa: ANN401
        name: str,
        do_raise: bool = False
    ) -> bool:
        if self.is_any:
            return True

        if self.is_union:
            return self._union_check(obj, name, do_raise)

        if self.is_literal:
            if obj not in self.literal_values:
                if do_raise:
                    # TODO: raise exception
                    ...
                return False
            return True

        if not isinstance(obj, self.type):
            if do_raise:
                _raise_type_error(name, self.type, obj)
            return False

        if self.is_callable:
            return self._callable_check(obj, name, do_raise)

        if len(self.sub_types) == 0:
            # Basic instance checked passed, we don't have any subtype so we'r
            # done.
            return True

        if self.is_type:
            if not issubclass(obj, self.sub_types):
                if do_raise:
                    ...
                return False
            return True

        if self.is_tuple:
            return self._tuple_check(obj, name, do_raise)

        if self.is_mapping:
            return self._mapping_check(obj, name, do_raise)

        if self.is_sequence:
            return self._sequence_check(obj, name, do_raise)

        return False

    def _check_class(self, cls: Type[Any], do_raise: bool = False) -> bool:
        # TODO: implement further
        return issubclass(cls, self.type) if self.type is not None else False

    def check(
        self,
        obj: Any,  # noqa: ANN401
        name: str = '',
        do_raise: bool = False
    ) -> bool:
        if isinstance(obj, type):
            return self._check_class(obj,  do_raise=do_raise)
        return self._check_instance(obj, name, do_raise=do_raise)


class TypeInfoCollection(Mapping):
    """
    TypeInfoCollection is a mapping that holds type information
    of a complex structured type
    """

    def __getitem__(self, key: str) -> Any:
        return self._members.__getitem__(key)

    def __len__(self) -> int:
        return len(self._members)

    def __init__(self, cls: Type[Any]) -> None:
        if not isinstance(cls, type):
            msg = (
                f'cls argument of {self.__class__.__name__} must by a '
                f'type but is an instance of {cls.__class__.__name__}'
            )
            raise TypeError(msg)

        self._type = cls

        hints = get_type_hints(cls, include_extras=True)
        self._members = {n: TypeInfo(h) for n, h in hints.items()}

    def check(self, obj: Any) -> bool:  # noqa: ANN401
        if not isinstance(obj, self._type):
            return False

        for mem, ti in self._members.items():
            if not hasattr(obj, mem) or not ti.check(getattr(obj, mem)):
                return False

        return True


if __name__ == '__main__':

    t = TypeInfo(...)
