from __future__ import annotations

import sys
from collections.abc import Callable, Collection, Mapping, Sequence
from types import GenericAlias
from typing import (
    _SpecialForm,
    Annotated,
    Any,
    ClassVar,
    Iterator,
    Literal,
    NoReturn,
    Optional,
    Tuple,
    Type,
    TypeVar,
    Union,
    # This is required for old annotations like Dict[str, int], List[int],
    # etc. Newer python versions use dict[str, int] or list[int].
    _GenericAlias,  # type: ignore
    get_args,
    get_origin
)

from pytypeinfo.typing import NoneType, UnionType, get_type_hints


# -----------------------------------------------------------------------------
# Constants
# -----------------------------------------------------------------------------

_IMMUTABLE_TYPES: set[type] = {
    Collection,
    Mapping,
    Sequence,
    tuple
}

_META_ATTR = '__metadata__'
_BOUND_ATTR = '__bound__'
_CONSTRAINTS_ATTR = '__constraints__'

# -----------------------------------------------------------------------------
# Types
# -----------------------------------------------------------------------------

_HINT_TYPE = Any

_ARG_TYPES = (type, _GenericAlias, GenericAlias, _SpecialForm)

# -----------------------------------------------------------------------------
# Functions
# -----------------------------------------------------------------------------

if sys.version_info < (3, 9):
    def _is_annotation(hint: Any) -> bool:  # noqa: ANN401
        meta = getattr(hint, '__metadata__', None)
        return isinstance(meta, Sequence) and len(meta) > 0

else:
    def _is_annotation(hint: Any) -> bool:  # noqa: ANN401
        return get_origin(hint) is Annotated


def _resolve_sub_types(hint: _HINT_TYPE) -> Tuple[TypeInfo, ...]:
    sub_types = []
    for arg in get_args(hint):
        if isinstance(arg, _ARG_TYPES) or arg is Ellipsis:
            sub_types.append(TypeInfo(arg))
    return tuple(sub_types)


def _raise_type_error(
    required_type: Type[Any],
    obj: Any            # noqa: ANN401
) -> NoReturn:
    msg = (
        f'Invalid type: object must be {required_type.__name__!r} but'
        f' is {type(obj).__name__!r}'
    )
    raise TypeError(msg)


def _raise_member_error(
    required_member: str,
    obj: Any            # noqa: ANN401
) -> NoReturn:
    msg = (
        f'Object of type {type(obj).__name__!r} is missing member '
        f'{required_member!r}'
    )
    raise KeyError(msg)


def _raise_length_error(
    expect_len: int,
    actual_len: int,
    name: str
) -> NoReturn:
    name = (' ' + name).strip()
    msg = (
        f'Invalid length:{name} length is {actual_len} '
        f'but must be {expect_len}'
    )
    raise ValueError(msg)


def _raise_class_error(
    required_class: Optional[Type],
) -> NoReturn:
    if required_class is None:
        msg = 'Object must be a class'
    else:
        msg = (
            f'Object must be class {required_class.__name__!r} '
            'or subclass thereof'
        )
    raise TypeError(msg)


# -----------------------------------------------------------------------------
# Classes
# -----------------------------------------------------------------------------

class TypeInfo(Mapping):
    """
    The TypeInfo class analyses a hint generated by the `get_type_hints`
    function from typing.py.
    """

    _map: Optional[dict[str, Any]]
    """Internal dict mapping slot names to values"""

    call_params: tuple[TypeInfo, ...]
    """Tuple of TypeInfo objects describing the parameters of a callable."""

    call_returns: Optional[TypeInfo]
    """
    Tuple of TypeInfo objects describing the return parameters of a callable.
    """

    is_annotation: bool
    """
    Flag: If True object is an Annotated type.
    See: https://docs.python.org/3/library/typing.html#typing.Annotated
    """

    is_any: bool
    """
    Flag: If True object can be Any object
    See: https://docs.python.org/3/library/typing.html#typing.Any
    """

    is_callable: bool
    """Flag: If True object is a callable"""

    is_class: bool
    """Flag: If True object is a class"""

    is_class_var: bool
    """
    Flag: If True object is a ClassVar.
    See: https://docs.python.org/3/library/typing.html#typing.ClassVar
    """

    is_ellipsis: bool
    """
    Flag: If True object is the builtin Ellipses type (...)
    See: https://docs.python.org/3/library/stdtypes.html#the-ellipsis-object
    """

    is_literal: bool
    """
    Flag: If True object has a concrete value
    See: https://typing.python.org/en/latest/spec/literal.html
    """

    is_mapping: bool
    """Flag: If True object is Mapping"""

    is_immutable: bool
    """Flag: If True object is immutable"""

    is_none: bool
    """Flag: If True object is NoneType"""

    is_sequence: bool
    """Flag: If True object is a Sequence"""

    is_strict: bool
    """
    Flag: If True TypeVar is strict (has constraint types). If False has no
          types specified or bound types.
    See: https://docs.python.org/3/library/typing.html#typing.TypeVar
    """

    is_tuple: bool
    """Flag: If True object is a tuple"""

    is_type: bool
    """Flag: If True object is a type"""

    is_type_var: bool
    """
    Flag: If True object is a TypeVar
    See: https://typing.python.org/en/latest/spec/literal.html
    """

    is_union: bool
    """Flag: If True object can be one of a selection of predefined types"""

    literal_values: tuple[Any, ...]
    """Tuple of concrete values an. Object must be one of these values."""

    metadata: tuple[Any, ...]
    """
    Tuple of metadata for an Annotated type.
    See: https://docs.python.org/3/library/typing.html#typing.Annotated
    """

    origin: Optional[Type]
    """
    Result of the get_origin method.
    See: https://docs.python.org/3/library/typing.html#typing.get_origin
    """

    sub_types: tuple[TypeInfo, ...]
    """Tuple of TypeInfo objects describing possible subtypes"""

    type: Optional[Type[Any] | UnionType]
    """Actual type of the object"""

    __slots__ = (
        '_map',
        'call_params',
        'call_returns',
        'is_annotation',
        'is_any',
        'is_callable',
        'is_class',
        'is_class_var',
        'is_ellipsis',
        'is_immutable',
        'is_literal',
        'is_mapping',
        'is_none',
        'is_sequence',
        'is_strict',
        'is_tuple',
        'is_type',
        'is_type_var',
        'is_union',
        'literal_values',
        'metadata',
        'origin',
        'sub_types',
        'type'
    )

    def _repr(self, with_prefix: bool = False) -> str:
        result = f'{self.__class__.__name__}: ' if with_prefix else ''

        if self.is_type_var:
            result += 'TypeVar'
            if len(self.sub_types) > 0:
                result += f'[{" | ".join(v._repr() for v in self.sub_types)}]'
            return result

        if self.is_class_var:
            ts = self.type.__name__ if self.type is not None else 'Any'
            if len(self.sub_types) > 0:
                ts += f'[{", ".join(v._repr() for v in self.sub_types)}]'
            result += f'ClassVar[{ts}]'
            return result

        if self.type is None:
            if self.is_ellipsis:
                result += '...'
            elif self.is_none:
                result += 'None'
            elif self.is_literal:
                lt = ', '.join(repr(v) for v in self.literal_values)
                result += f'Literal[{lt}]'
            elif self.is_any:
                result += 'Any'

            # TODO: what else can this be?
            return result

        sub_types = None
        if len(self.sub_types):
            sub_types = ', '.join((st._repr(False) for st in self.sub_types))

        if self.is_union:
            return result + f'Union[{sub_types}]'

        result += self.type.__name__
        if sub_types is not None:
            result += f'[{sub_types}]'

        if self.is_callable:
            params = ', '.join((p._repr(False) for p in self.call_params))
            ret_type = self.call_returns._repr(False)
            result += f'[[{params}], {ret_type}]'

        return result

    def __repr__(self) -> str:
        return self._repr(with_prefix=True)

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, TypeInfo):
            return False

        for attr in TypeInfo.__slots__:
            if getattr(self, attr) != getattr(other, attr):
                return False

        for st_me, st_o in zip(self.sub_types, other.sub_types):
            if st_me != st_o:
                return False

        return True

    def __iter__(self) -> Iterator:
        if self._map is None:
            self._map_init()
        return self._map.__iter__()

    def __len__(self) -> int:
        if self._map is None:
            self._map_init()
        return self._map.__len__()

    def __getitem__(self, key: str) -> Any:
        if self._map is None:
            self._map_init()
        return self._map.__getitem__(key)

    def __hash__(self) -> int:
        # TODO: calculate proper hash
        return 0

    def _slot_init(self, hint: _HINT_TYPE) -> None:
        self._map = None
        self.type = None
        self.origin = None
        self.sub_types = ()
        self.is_any = hint is Any
        self.is_type = False
        self.is_mapping = False
        self.is_immutable = False
        self.is_sequence = False
        self.is_tuple = False
        self.is_none = hint is NoneType or hint is None
        self.is_ellipsis = hint is Ellipsis
        self.is_annotation = False
        self.is_class = False
        self.is_class_var = False
        self.is_type_var = False
        self.is_strict = False
        self.is_union = False
        self.is_literal = False
        self.literal_values: tuple[Any, ...] = ()
        self.is_callable = False
        self.call_params = ()
        self.call_returns = None
        self.metadata: tuple[Any, ...] = ()

    def _map_init(self) -> None:
        self._map = {
            s: getattr(self, s) for s in self.__slots__ if s[0] != '_'
        }

    def __init__(self, hint: _HINT_TYPE) -> None:
        """
        :@param hint:           A type hint generated by calling typings.py
                                `get_type_hints` function.
        """
        self._slot_init(hint)
        if self.is_any or self.is_none or self.is_ellipsis:
            return

        self.origin = get_origin(hint)
        self.is_type = isinstance(hint, type) or isinstance(self.origin, type)
        self.is_class_var = self.origin is ClassVar or hint is ClassVar
        self.is_literal = self.origin is Literal
        self.is_type_var = isinstance(hint, TypeVar)
        self.is_annotation = _is_annotation(hint)
        self.is_union = self.origin in (Union, UnionType)
        self.is_class = hint is type or self.origin is type

        if self.is_annotation or self.is_class_var:
            self.metadata = getattr(hint, _META_ATTR, ())
            sub_types = _resolve_sub_types(hint)
            if len(sub_types) > 0:
                self.is_type = True
                self.type = sub_types[0].type
                self.sub_types = sub_types[0].sub_types
            else:
                # Non-generic class var becomes any automatically
                self.is_any = True
            self.origin = None

        elif self.is_literal:
            self.literal_values = get_args(hint)

        elif self.is_union:
            self.type = UnionType
            self.is_type = True
            self.sub_types = _resolve_sub_types(hint)
            self.origin = None

        elif self.is_type:
            self.type = self.origin or hint
            self.sub_types = _resolve_sub_types(hint)
            self.is_immutable = self.type in _IMMUTABLE_TYPES
            self.is_mapping = issubclass(self.type, Mapping)
            self.is_sequence = issubclass(self.type, Sequence)
            if self.origin == self.type:
                self.origin = None

        elif self.is_type_var:
            bound = getattr(hint, _BOUND_ATTR, None)
            if bound is not None:
                self.sub_types = (TypeInfo(bound),)

            const = getattr(hint, _CONSTRAINTS_ATTR, None)
            if const is not None and const != ():
                self.sub_types = tuple((TypeInfo(c) for c in const))
                self.is_strict = True
            return

        self.is_callable = self.type is Callable
        if self.is_callable:
            param, return_type = get_args(hint)
            if not isinstance(param, Sequence):
                param = (param,)
            self.call_params = tuple([TypeInfo(a) for a in param])
            self.call_returns = TypeInfo(return_type)
            self.sub_types = ()
            return

        if self.is_class and self.sub_types == ():
            # 'Type' hint without parameter becomes Type[Any]
            self.is_any = True

        self.is_tuple = self.type is tuple

    def _union_check(
        self,
        obj: Any,  # noqa: ANN401
        name: str,
        do_raise: bool = False
    ) -> bool:
        for ti in self.sub_types:
            if ti._check_instance(obj, name, do_raise):
                return True
        return False

    def _tuple_check(
        self,
        obj: Any,  # noqa: ANN401
        name: str,
        do_raise: bool = False
    ) -> bool:
        _type = self.sub_types[0]
        num_sub_types = len(self.sub_types)
        if _type.is_ellipsis:
            # tuple[...] -> Variable length and any type allowed
            return True

        if num_sub_types == 2 and self.sub_types[1].is_ellipsis:  # noqa: PLR2004

            return self._sequence_check(obj, name, do_raise)

        if len(self.sub_types) != len(obj):
            if do_raise:
                _raise_length_error(len(self.sub_types), len(obj), name)
            return False

        for index, (tpl_type, obj_item) in enumerate(zip(self.sub_types, obj)):
            if not tpl_type.check(obj_item, f'{name}[{index}]', do_raise):
                return False

        return True

    def _sequence_check(
        self,
        obj: Sequence[Any],
        name: str,
        do_raise: bool = False
    ) -> bool:
        if self.type is str:
            return isinstance(obj, str)

        if len(self.sub_types) == 0:
            return True

        value_type = self.sub_types[0]
        for index, value in enumerate(obj):
            if not value_type.check(
                value,
                f'{name}[{index}]',
                do_raise=do_raise
            ):
                return False
        return True

    def _mapping_check(
        self,
        obj: Mapping[Any, Any],
        name: str,
        do_raise: bool = False
    ) -> bool:
        key_type, value_type = self.sub_types
        for key, value in obj.items():
            if not key_type.check(key, name):
                if do_raise:
                    ...
                return False
            if not value_type.check(
                value,
                f'{name}[{key}]',
                do_raise=do_raise
            ):
                return False
        return True

    def _callable_check(
        self,
        obj: Callable,
        name: str,          # noqa  TODO: raise error with callable name
        do_raise: bool = False
    ) -> bool:
        hints = get_type_hints(obj)
        call_return = TypeInfo(hints.pop('return', None))
        call_params = tuple((TypeInfo(p) for p in hints.values()))

        if len(self.call_params) > 0 and self.call_params[0].is_ellipsis:
            return self.call_returns == call_return

        if self.call_returns == call_return and \
           self.call_params == call_params:
            return True

        if do_raise:
            ...

        return False

    def _type_check(
        self,
        obj: Type,
        name: str,
        do_raise: bool = False
    ) -> bool:
        if not isinstance(obj, self.type):
            if do_raise:
                _raise_type_error(name, self.type, obj)
            return False

        # TODO: sub type check with __orig_class__. This allows to check
        #       something like MyGenericClass[int]

        return True

    def _check_instance(  # noqa: PLR0911  TODO: simplify code
        self,
        obj: Any,  # noqa: ANN401
        name: str,
        do_raise: bool = False
    ) -> bool:
        # Order of checks is important
        if self.is_any:
            return True

        if self.is_union:
            return self._union_check(obj, name, do_raise)

        if self.type is not None and not isinstance(obj, self.type):
            return False

        if self.is_literal:
            if obj not in self.literal_values:
                if do_raise:
                    # TODO: raise exception
                    ...
                return False
            return True

        if self.is_callable:
            return self._callable_check(obj, name, do_raise)

        if self.is_tuple:
            return self._tuple_check(obj, name, do_raise)

        if self.is_mapping:
            return self._mapping_check(obj, name, do_raise)

        if self.is_sequence:
            return self._sequence_check(obj, name, do_raise)

        if self.is_type:
            return self._type_check(obj, name, do_raise)

        return False

    def _check_class(
        self,
        cls: Type[Any],
        name: str = '',
        do_raise: bool = False
    ) -> bool:
        if not isinstance(cls, type):
            if do_raise:
                _raise_class_error(
                    None if self.is_any else self.sub_types[0].type
                )
            return False

        if self.is_any:
            return True

        if self.sub_types != ():
            # TODO: Add strict type checking
            if not issubclass(cls, self.sub_types[0].type):
                if do_raise:
                    _raise_class_error(self.sub_types[0].type)
                return False
            return True

        return False

    def check(
        self,
        obj: Any,  # noqa: ANN401
        name: str = '',
        do_raise: bool = False
    ) -> bool:
        if self.is_class:
            return self._check_class(obj,  do_raise=do_raise)
        return self._check_instance(obj, name, do_raise=do_raise)


class TypeInfoCollection(Mapping):
    """
    TypeInfoCollection is a mapping that holds type information
    of a complex structured type
    """
    __slots__ = [
        '_infos',
        '_type'
    ]

    def __iter__(self) -> Iterator:
        return self._infos.__iter__()

    def __getitem__(self, key: str) -> TypeInfo:
        return self._infos[key]

    def __len__(self) -> int:
        return len(self._infos)

    def __init__(self, cls: Type[Any]) -> None:
        # TODO: Add recursive checking
        if not isinstance(cls, type):
            msg = (
                f'cls argument of {self.__class__.__name__} must by a '
                f'type but is an instance of {cls.__class__.__name__}'
            )
            raise TypeError(msg)

        self._type = cls

        hints = get_type_hints(cls, include_extras=True)
        self._infos = {n: TypeInfo(h) for n, h in hints.items()}

    def check(
        self,
        obj: Any,    # noqa: ANN401
        accept_other: bool = False,
        do_raise: bool = False,
    ) -> bool:
        """
        Check an object for conformity to a TypeInfoCollection. Object must
        have members with same name and type.

        :param obj:             The object to check
        :param accept_other:    Object can be of different type but must have
                                the same typed members
        :param do_raise:        raise an exception when check fails

        :return:                True if check is successful.
        """
        if not accept_other and not isinstance(obj, self._type):
            if do_raise:
                _raise_type_error(self._type, obj)
            return False

        obj_name = type(obj).__name__
        for name, ti in self._infos.items():
            if not hasattr(obj, name):
                if do_raise:
                    _raise_member_error(name, obj)
                return False

            if not ti.check(
                getattr(obj, name),
                name=f'{obj_name}.{name}',
                do_raise=do_raise
            ):
                return False

        return True

    def diagnose(
        self
    ) -> str:
        # TODO: Implement detailed diagnostic for type errors
        ...
